branches:
  only:
    - master
language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v2.1.0
- iojs-v1.0.4
services:
- mongodb
script: npm run test-travis
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: eKiNuomt+K0pLUPZAdevvfvAdGPAKszvaPRAMmpid1XS244/pCk4ORQ9e6XcHO0m/uZXB+WzWybUwpjyy8EKjFtkN+411UQqb7Ym57K81U5EbBVdZibw15gVjPKsz3n+WocBSuVbYpt2l71TuFquS+tX13U/WPL89tPuZOs5dJE=
