language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs-v2.1.0
- iojs-v1.0.4
services:
- mongodb
notifications:
  slack:
    secure: NiKZh2wicxt4qLUWTUKlPHiLuQjN1yIB6f8T3f1zvQf9cFakpGeKNlFnGVgKTjROIecxu5q2X09jHQtj5b9VlFoXUFA6Shg4P9VXUnw6Tk7UJTY69catzOn5QBw9blsqgoxQX7at3yMqHULCs8bu1OyWUIa+FSiCQUknwNPNqDo=
