branches:
  only:
    - master
    - develop
language: node_js
node_js:
- '5.2.0'
- '5.1.1'
- '5.1.0'
- '5.0.0'
- '4.2.3'
services:
- mongodb
script: npm run test-travis
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack:
    secure: eKiNuomt+K0pLUPZAdevvfvAdGPAKszvaPRAMmpid1XS244/pCk4ORQ9e6XcHO0m/uZXB+WzWybUwpjyy8EKjFtkN+411UQqb7Ym57K81U5EbBVdZibw15gVjPKsz3n+WocBSuVbYpt2l71TuFquS+tX13U/WPL89tPuZOs5dJE=
